auctions/urls.py
from django.urls import path, re_path
from django.views.generic.base import RedirectView

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    re_path(r'^all/?$', views.all_listings, name="all_listings"),
    re_path(r'^my-listings/?$', views.my_listings, name="my_listings"),
    re_path(r'^my-watchlist/?$', views.watchlist, name="watchlist"),
    re_path(r'^new/?$', views.new_listing, name="new_listing"),
    re_path(r'^listing/(?P<listing_id>[0-9]+)/?$', views.listing_page, name="listing_page"),
    re_path(r"^login/?$", views.login_view, name="login"),
    re_path(r"^logout/?$", views.logout_view, name="logout"),
    re_path(r"^register/?$", views.register, name="register"),
    re_path(r'^.+/?$', RedirectView.as_view(pattern_name='auctions:index', permanent=True))
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from colorfield.fields import ColorField
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    category_name = models.CharField(max_length=20)
    color = ColorField(default='#ffffff')
    color_text = ColorField(default='#000000')

    def __str__(self):
        return f'{self.category_name}'


class Listing(models.Model):
    class ListingState(models.TextChoices):
        ACTIVE = 'A', _('Active')
        CLOSED = 'C', _('Closed')

    title = models.CharField(max_length=100)
    starting_price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    state = models.CharField(
        max_length=1, choices=ListingState.choices, default=ListingState.ACTIVE)
    image_url = models.URLField(blank=True, null=True)
    category = models.ForeignKey(
        'Category', blank=True, on_delete=models.SET_NULL, null=True, related_name='listing_category')
    user = models.ForeignKey(
        'User', on_delete=models.CASCADE, related_name='listing_user')
    bids = models.ManyToManyField('User', through='Bid', related_name='listing_bids')
    comments = models.ManyToManyField(
        'User', through='Comment', related_name='listing_comments')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}'


class Bid(models.Model):
    listing = models.ForeignKey(
        'Listing', on_delete=models.CASCADE, related_name='bid_listing')
    user = models.ForeignKey(
        'User', on_delete=models.CASCADE, related_name='bid_user')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'${self.price}'


class Comment(models.Model):
    listing = models.ForeignKey(
        'Listing', on_delete=models.CASCADE, related_name='comment_listing')
    user = models.ForeignKey(
        'User', on_delete=models.CASCADE, related_name='comment_user')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.content}'


class User(AbstractUser):
    watchlist = models.ManyToManyField(
        'Listing', blank=True, related_name='user_watchlist')

    def __str__(self):
        return f'{self.first_name} {self.last_name} a.k.a. {self.username}'

auctions/views.py
from decimal import Decimal

from django import forms
from django.forms.utils import ErrorList
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import Max
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import User, Listing, Category, Comment, Bid


# Forms

class DivErrorList(ErrorList):
    def __str__(self):
        if not self:
            return ''
        return '<div class="errorlist alert alert-danger">%s</div>' % \
            ''.join(['<div class="error">%s</div>' % e for e in self])


class TextAreaForm(forms.Form):
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'class': 'form-control',
        'rows': 4,
        'placeholder': 'Add your comment here...',
        'required': True}))


class InputForm(forms.Form):
    bid_price = forms.CharField(label='', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'number',
        'placeholder': 'Place your Bid (0.00)*',
        'step': 0.01,
        'min': 0.01,
        'required': True}))


# Views

def index(request):
    if request.method == "POST":
        return _add_remove_from_watchlist(request, index.__name__)
    else:
        listings = Listing.objects.filter(state='A').order_by('-created_at')
        _include_highest_bid_listings(listings)
        return render(request, "auctions/index.html", {
            "listings": listings,
            "url_view": reverse("auctions:index")
        })


def all_listings(request):
    if request.method == "POST":
        return _add_remove_from_watchlist(request, all_listings.__name__)
    else:
        cat = request.GET.get('cat', '')
        listings = []
        if cat:
            if not cat.isdigit():
                if cat.lower() != 'none':
                    return HttpResponseRedirect(reverse("auctions:all_listings"))
                else:
                    listings = Listing.objects.filter(category__isnull=True)
            else:
                listings = Listing.objects.filter(category=cat)
        else:
            listings = Listing.objects.all()
        listings = listings.order_by('state', '-created_at')
        _include_highest_bid_listings(listings)
        categories = Category.objects.all()
        return render(request, "auctions/all_listings.html", {
            "listings": listings,
            "categories": categories,
            "url_view": reverse("auctions:all_listings")
        })


@login_required()
def my_listings(request):
    if request.method == "POST":
        return _add_remove_from_watchlist(request, my_listings.__name__)
    else:
        listings = Listing.objects.filter(
            user=request.user).order_by('-created_at')
        _include_highest_bid_listings(listings)
        return render(request, "auctions/my_listings.html", {
            "listings": listings,
            "url_view": reverse("auctions:my_listings")
        })


@login_required()
def watchlist(request):
    if request.method == "POST":
        return _add_remove_from_watchlist(request, watchlist.__name__)
    else:
        listings = Listing.objects.filter(
            user_watchlist=request.user).order_by('state', '-created_at')
        _include_highest_bid_listings(listings)
        return render(request, "auctions/watchlist.html", {
            "listings": listings,
            "url_view": reverse("auctions:watchlist")
        })


def _include_highest_bid_listings(listings):
    for l in listings:
        l.highest_bid = _get_highest_bid(l)[0]


def _get_highest_bid(l):
    all_bids = l.bid_listing.all()
    return (max(all_bids, key=lambda x: x.price) if all_bids else None, all_bids.count())


def _add_remove_from_watchlist(request, view):
    if 'btn_remove_watchlist' in request.POST or \
            'btn_add_watchlist' in request.POST:
        _add_remove_from_watchlist_helper(request, request.POST["listing_id"])
    return HttpResponseRedirect(reverse(f"auctions:{view}"))


def _add_remove_from_watchlist_helper(request, listing_id):
    try:
        listing = Listing.objects.get(pk=listing_id)
        user = request.user
    except KeyError:
        return HttpResponseBadRequest("Bad Request: no listing chosen")
    except Listing.DoesNotExist:
        return HttpResponseBadRequest("Bad Request: listing does not exist")
    except User.DoesNotExist:
        return HttpResponseBadRequest("Bad Request: user does not exist")
    if 'btn_remove_watchlist' in request.POST:
        user.watchlist.remove(listing)
    elif 'btn_add_watchlist' in request.POST:
        user.watchlist.add(listing)


@ login_required()
def new_listing(request):
    if request.method == "POST":
        try:
            category_request = request.POST['category']
            image_request = request.POST['image_url']
            new_listing = Listing(
                title=request.POST['title'],
                description=request.POST['description'],
                category=(Category.objects.get(
                    pk=category_request) if category_request else None),
                starting_price=Decimal(request.POST['starting_price']),
                image_url=(image_request if image_request else None),
                user=request.user)
            new_listing.save()
            return HttpResponseRedirect(reverse("auctions:my_listings"))
        except:
            return HttpResponseBadRequest("Bad Request")
    else:
        categories = Category.objects.all()
        return render(request, "auctions/new_listing.html", {
            "categories": categories
        })


def listing_page(request, listing_id):
    try:
        listing = Listing.objects.get(pk=listing_id)
        listing.highest_bid, listing.total_bids = _get_highest_bid(listing)
        comment_list = listing.comment_listing.all().order_by('-created_at')
        if request.method == "POST":
            if 'btn_remove_watchlist' in request.POST or \
                    'btn_add_watchlist' in request.POST:
                _add_remove_from_watchlist_helper(request, listing_id)
                return redirect("auctions:listing_page", listing_id=listing_id)
            elif 'btn_post_comment' in request.POST:
                textarea_form = TextAreaForm(
                    request.POST, error_class=DivErrorList)
                if textarea_form.is_valid():
                    content = textarea_form.cleaned_data["content"]
                    comment = Comment(
                        listing=listing, user=request.user, content=content)
                    comment.save()
                    return redirect("auctions:listing_page", listing_id=listing_id)
                else:
                    return render(request, "auctions/listing.html", {
                        "listing": listing,
                        "textarea_form": textarea_form,
                        "input_form": InputForm(),
                        "comments": comment_list
                    })
            elif 'btn_place_bid' in request.POST:
                input_form = InputForm(request.POST, error_class=DivErrorList)
                if input_form.is_valid():
                    bid_price = input_form.cleaned_data["bid_price"]
                    current_price = listing.highest_bid.price if listing.highest_bid else listing.starting_price
                    if current_price >= Decimal(bid_price):
                        return render(request, "auctions/listing.html", {
                            "listing": listing,
                            "input_form": input_form,
                            "textarea_form": TextAreaForm(),
                            "input_message": "Your bid has to be higher than the current price!",
                            "comments": comment_list
                        })
                    else:
                        bid = Bid(listing=listing, user=request.user,
                                  price=bid_price)
                        bid.save()
                else:
                    return render(request, "auctions/listing.html", {
                        "listing": listing,
                        "input_form": input_form,
                        "textarea_form": TextAreaForm(),
                        "comments": comment_list
                    })
            elif 'btn_close_auction' in request.POST:
                listing.state = 'C'
                listing.save(update_fields=['state'])
            return redirect("auctions:listing_page", listing_id=listing_id)
        else:
            return render(request, "auctions/listing.html", {
                "listing": listing,
                "input_form": InputForm(),
                "textarea_form": TextAreaForm(),
                "comments": comment_list
            })
    except KeyError:
        return HttpResponseBadRequest("Bad Request: no listing chosen")
    except Listing.DoesNotExist:
        return render(request, "auctions/listing.html", {
            "listing": None,
        })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            next_param = request.POST.get('next', '')
            redirect_to = next_param if next_param else reverse(
                "auctions:index")
            return HttpResponseRedirect(redirect_to)
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):

auctions/templates/auctions/all_listings.html
{% extends "auctions/listing_template.html" %}

{% block title_listings %}
    <h1 class="text-center">
        {% if category_name %}
            {{ category_name }}
        {% else %}
            All
        {% endif %}
         Listings
    </h1>
{% endblock %}

{% block categories %}
    <div class="mb-4 pr-4 text-right">
        <div class="btn-group" role="group">
            <a type="button" class="btn btn-info btn-lg" href="{% url 'auctions:all_listings' %}">Categories</a>
            <button type="button" class="btn btn-info btn-lg dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item text-center" href="{% url 'auctions:all_listings' %}?cat=None">
                    ----- None -----
                </a>
                {% for category in categories %}
                    <a class="dropdown-item" href="{% url 'auctions:all_listings' %}?cat={{category.id}}">
                        {{ category.category_name }}
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block title_empty_listings %}
    <h3 class="text-center">No listings available from this category.</h3>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/listing_template.html" %}

{% block title_listings %}
    <h1 class="text-center">Active Listings</h1>
{% endblock %}

{% block title_empty_listings %}
    <h3 class="text-center">No active listings available.</h3>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>{% block title %}Auctions{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% comment %} <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet"> {% endcomment %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round|Material+Icons+Outlined" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    {% block custom_styles %}
    {% endblock %}
</head>

<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: #003773;">
        <span class="navbar-text">
            <i class="material-icons-round md-48 md-light">gavel</i>
        </span>
        <span class="navbar-brand md-48">
            Auctions
        </span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarAuctions" aria-controls="navbarAuctions" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarAuctions">
            <ul class="navbar-nav mx-auto justify-content-around w-100">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:all_listings' %}">All Listings</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:new_listing' %}">Create Listing</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <div class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownAuctions" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <div class="navbar-text">
                                <i class="material-icons-outlined md-light" style="font-size: 20px; vertical-align: text-top">
                                    account_circle
                                </i>
                            </div>
                            <span class="navbar-brand" style="font-size: 24px">
                                Hello, <strong>{{ user.first_name }}</strong>
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right text-center" aria-labelledby="dropdownAuctions">
                            <a class="dropdown-item" href="{% url 'auctions:watchlist' %}">My Watchlist</a>
                            <a class="dropdown-item" href="{% url 'auctions:my_listings' %}">My Listings</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'auctions:logout' %}">Log Out</a>
                        </div>
                    </li>
                </div>
            {% else %}
                <div class="text-center">
                    <span class="navbar-brand">
                        Not signed in.
                    </span>
                </div>
            {% endif %}
        </div>
    </nav>
    <div class="body-container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script>
        $(function() {
            // get current URL path and assign 'active' class
            var pathname = window.location.pathname;
            $('nav.navbar ul.navbar-nav>li.nav-item>a[href="' + pathname + '"]').parent().addClass('active');
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>

</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block custom_styles %}
    <link href="{% static 'auctions/login_register.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Auctions - Login
{% endblock %}

{% block body %}
    <div class="card mx-auto text-center mt-4 mx-4">
        <h1>Login</h1>
        {% if message %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endif %}
        <div class="card-body">
            <form action="{% url 'auctions:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input autofocus class="form-control text-center" type="text" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input class="form-control text-center" type="password" name="password" placeholder="Password">
                </div>
                <button class="btn btn-primary btn-lg" type="submit">Login</button>
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
            </form>
        </div>
        <div class="card-footer">
            Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/my_listings.html
{% extends "auctions/listing_template.html" %}

{% block title_listings %}
    <h1 class="text-center">My Listings</h1>
{% endblock %}

{% block title_empty_listings %}
    <h3 class="text-center">You don't have any listings posted.</h3>
{% endblock %}

auctions/templates/auctions/new_listing.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block custom_styles %}
    <link href="{% static 'auctions/new_listing.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="card mx-auto text-center mt-4 mx-4">
        <h1>Create new Listing</h1>
        {% if message %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endif %}
        <div class="card-body">
            <form id="newListingForm" action="{% url 'auctions:new_listing' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" autofocus type="text" name="title" placeholder="Title*" required>
                </div>
                <div class="form-group">
                    <textarea class="form-control" name="description"
                        placeholder="Description*" rows="10" cols="50" required></textarea>
                </div>
                <div class="form-group">
                    <select class="form-control" name="category">
                        <option value="">Select Category</option>
                        {% for category in categories %}
                            <option value="{{category.id}}">{{ category.category_name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-success" style="color: #fff">$</span>
                        </div>
                        <input class="form-control" type="number" name="starting_price"
                            placeholder="Starting Bid (0.00)*" step="0.01" min="0.01" required">
                    </div>
                </div>
                <div class="form-group">
                    <input class="form-control" type="url" name="image_url" placeholder="Image URL">
                </div>
            </form>
        </div>
        <div class="card-footer">
            <button class="btn btn-success btn-block" type="submit"
                form="newListingForm" style="font-size: 20px;">
                Submit
            </button>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block custom_styles %}
    <link href="{% static 'auctions/login_register.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}
    Auctions - Register
{% endblock %}

{% block body %}
    <div class="card mx-auto text-center mt-4 mx-4">
        <h1>Register</h1>
        {% if message %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endif %}
        <div class="card-body">
            <form action="{% url 'auctions:register' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" autofocus type="text" name="first_name" placeholder="First Name">
                </div>
                <div class="form-group">
                    <input class="form-control" type="text" name="last_name" placeholder="Last Name">
                </div>
                <div class="form-group">
                    <input class="form-control" type="text" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input class="form-control" type="email" name="email" placeholder="Email Address">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="Password">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
                </div>
                <button class="btn btn-primary btn-lg" type="submit">Register</button>
            </form>
        </div>
        <div class="card-footer">
            Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/listing_template.html" %}

{% block title_listings %}
    <h1 class="text-center">My Watchlist</h1>
{% endblock %}

{% block title_empty_listings %}
    <h3 class="text-center">You don't have any listings in your watchlist.</h3>
{% endblock %}